apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phone-numbers
  namespace: quotes
spec:
  encryptedData:
    numbers: AgAXYCehGg9MsBrg0VmQSdpPzg6eGdPO+2EmLfo3LBBSaijEF9WqmcSbLMgX7iu5LxZVn3tgCZd6Q8DLWg4apb++WjQ8lqRRZI3HloiBk0ieu4OEaGbYJGw20PvbdRmLtrYZHkhcDsx4SC+uZZi7vsrVuGix4rfrYLLLttyowDJ/I08sczD93EzQWd1V0ZaDzd3ptKEuMVwk4NTjZXwD8TUHoUsHvrps8r8qScOxWvzbPYtXLsgMo04+ea8+gl5k0V4RJfsmsgJntB7QlV7El69XrwU48odRDSOanxY3PlGXQcmYOzsd4M4WugwSPZnA7ntvxnBiUkGKCB/052Ppf1dQVCaxaCBu1xB/J3oZvy788rGGBFlRk8aWFkPQ5zwG+GMM8dL9ViM8qmtWc/8e/g15q+ddM5gldFHL9xLtsAuacE6JDJK5Odmfff4J7ZY4BkUb12MH9AwYeim5Rq4xVmZlCgQOQgNm8XfGy2QMKbOjjsygCC1eGFNP0foRzHQ591H4Cdc3msTX5OP3ETA/gfWvbTCaKhgXXrQHmLqDATjpviXXZTwafQf24Lr0cH6cakaKuWAni1qDyShMgvy05iv0IbiGQSTcU+8AiT4qhFmOxa7xHOn7+u6LuwvA8o988hYzX3xCIO6QH5WPzHplGM+nXFEEk8uVZopGekMq1LNAOjylQfTZVzQr9EblT52IHBComeCjMAs0PV0OeCcoNMOszXvMliAQCVqo7236DK9gNwPIWvA9dd5LZwizgldVQCmNR5uMi3/wqq5PzBi0UEBogurMpDb9Dd6L/aa8E8xpdlpvqRQdimVARn5zx14SEgbo7UQ65YDMmyivTnBSCKrYbcqkJbD3dnep0G7o807bCa46L5JWWK/Lp/vJrIx1GkOfZHyQAgL9pkGeuXjMCy23J0W1fI9BuCQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: phone-numbers
      namespace: quotes
