apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phone-numbers
  namespace: quotes
spec:
  encryptedData:
    numbers: AgAVLJEaXtP6z38xG7BkjlpeFmpdnwRKFBvw+goxsD4z6NLqWyeqtEgExvucbY1c61nzDckhHK2sKGkzaYcJ9B4rO2dX3UISairvrc+UQCy6a9uGmU8iDgO7+RN0kRvRYb2A6ohasvLxcHEYgIWs0ItVnzYb0bBXlJD+LDb2qrMWDdN3RiELgWLHU94pPvrJNm/QICv80xrr8v33jAtAEwbE3H/SmHFQuE2mqFnp/w7g8JoUDveiuqCtFP7HqZ07137ihdm4gukMHYvY631WwUPardotfe2vK1kXKf2IDSRzvBo89ZM2EsqitYTQrEFaVkXmcZyBUNuEj9K9QaFrPDxcRrjuDgNvKS72N3BYkn3r+rz3e2oplI/5aIjPhPq9KIS1zHmahrRnqKxLwBDAhCsiaYqafylw74q5bDhYDlFW/XzF9jbHJY9/kdXvA1XbiiVDHAaR6Oiyu2nOeeTjwnOwS2dkEzlWz5vDAjbO3/obLuMWlok9pPqnkysx2TkWvrS5tyFQn+gHpzsEB9EFp66XtGxXh1dfulklSt55T0DBYMzGFgD36SqvuRVGWOFXoPm2mAkTJfao2fUrLyYcCN2rLbKDlrDrO17TD51P6cDo5aK+H59RZ68wIT2bqVA35Eec0jpINbED4fIs9k2KyQZ5d447/Wtc7q7YdtVf5CDZIqr5ncj03nQGsHUmgZLF1peZG8T8n9gtmt9rUVORLijcw5UvP+5r608I4stNnU9tOS2If6y7cYVBq7Ftkotqk/RoMH1JlLMjgEg+mT04MK6EX6WIGxjpzp4+JUQQhyxd3j2CLFVjSsSRF27/TpeOGvApNz2vc/3A
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: phone-numbers
      namespace: quotes