apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phone-numbers
  namespace: quotes
spec:
  encryptedData:
    numbers: AgAox3wG64nKL8enOxF2ID4Yc6pxAEf+wIOZDvOmLeo5pWtGQde1szVsGQmzUNRgo9DciHb/Kj40ARDHXFU5Wz5FbH6gGfMMhDa+0t3xSTkQKxYnAGlbA0A5MI9OQS1IuvcuawiB3Y6bUCMUE7ekBVOCQJEiE8Hvihzk4PPafGisN1PEURUBKxVBUYEYq4fYf7a2izwI872bzb5HGyoYk31orzQP/GbZOvWzTCLqesW6u/fk2oOoHxdJ5CrzaWji46d4/zEXRu0Mj1DJW8/x05NzVRxHg9xfvBbWmtPXoB16ZThsSgCmWlyIeWAw5Ustdcoh9PfW5BrnEqZpuxtQpzjv6PNc3zOMs2ESxh1/xmZCcX4VuYE01/fjySBUY+9XW5egL8jhJDUYFjtxWcjtplxa73KkixxuCOU184b6M6jCH7XSaLpVEkXt3XlwQJVZ1r786rIfCR+1lozrUXRAh7umv7463rOde/0ZPnBLO8kxLCLr2FlqAPkygLDiexkspLYg/tTmnf4v/DFfkMTsnIh8m+Nqpep6Ae7AjMBMo6ZKst5P/ZtUc0csbmE6406MM1/5XK6QP0L7n3lq0crrQRJjvrIa1hol+zlraxfHY9+n/701AlO/w2YwignfUcmsoSu/ScZvsRxEJbVolOXL16vsHcbXHfc62hmtNA9JjftgIw+4Ny2IXtxjBZDymc04SEgjuMfs99HIr18jMmhes5xvb3x+okooD7+1UH5stK6kT0LgnZrMg8EWcsI9zBUXoiUeki2uCtoU27wnIR17hDF+cYbXPDBYqjjGA0zKfypXCWDQ6sKJ9yaz6ZU2evlgyysCZvz3rjcBHewz0BbP+uXoWBeo7m/FE3i9Y6r9UK6d6QfS6pXE0qsbTwqaTbjZLJ+Xbinzlr+LvMWBKS4/w7cKvp0pchgvRFm9MkUIqt6rv8H9k0DTIPKUx99S0iEqc/gN9A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: phone-numbers
      namespace: quotes

