apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phone-numbers
  namespace: quotes
spec:
  encryptedData:
    numbers: AgBABMUeNcAnYw3yeUQ8/qCyR2Zu2U96U8EqinBCPuhtPTWgyzx8fOFGWNsIOOItlcjsv4wNqkQS8zMbtMN/jAO+gUeUDzdgj8K3Q32HLBipm8bRFwQwlKwCGocUfu30U1/WkLWI8gmIGEGbuVRFo2bhNJSHFARqtTz/TQnwJGsMX3Xiq99e0c0zG9KyR7X7QZWSdomG4bls0YIO0dn/awjRU52pqDr7U/lTF28eCqOieivHQUN47LYY3i7Sc/042L5rvtb+ByaXxuDE7iYH/Z2W7RzQQZnqDHVX7xUcUotsLJZMbryCZF/sLUK1ehBM5akLv/NJ1WYKezW92PKCD9joSJLyFoLWg4QPMp1Y3MiPD5dFA270AZXRVUVKghKCY1nRkvB8DRumRCY53FKbk9cLU/sII/xnPw8FjEY47bfu770ty9irK+0HGDeLuNGnPOusf3gZzYxD6zMN+Nzsa7o5PebDJuQ+88H9kWukn+WMZrUjK0MADgWUJ71flWuHwe8RkdXoJNVFLLvXuCG5TlbtYBobAGhV/YOll31MPM3DBo2AStGvnt8/qA5J7s1RvAMz1BDNkDJOpLJDnskukkOSIbM2ugjdSu0BZYzNtIwY79Y0RQS0aTiHYElXOdC+yD2EAKlb2OqOl+ITd9WSl02VIEQbnqT8lioMZRpkodktVJuag+I0G+7Bn1tIT0O/GBxe59TFzWnclmkcwTaA+EwMkU5rK2CiiIQYI9A4wyVDbmQHfc3xiZ3LKjjTZI4kJhTxelvCJJF7xC4HAZY50hQeULXtTIOQ/yuPbTWBNQV6agO9WSaP9JjrghafaQKXw78K3hZRyxA+zwJxXgGIHjxFpIb6fvo8OYzdn75QbAE19iykuT3LYN/RA1y0o2i74t8cown4O0bYeEZPqBxmGDt4onPWbH0DbrI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: phone-numbers
      namespace: quotes

