apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: phone-numbers
  namespace: quotes
spec:
  encryptedData:
    numbers: AgBxQ0nqwXtxO3ioKdkMDIiFmjD6096w992jxMxT7yMlxqhmXHCPwRFcKSxqRoz0SvR7NeMnQbdPSI9VJuvAcDrKjVvmI2kKtFtAela62d9aOB9sDrWCnll0bZwHmGd6FPiEmZt4ecUj4pkGCl8D6QxqcfzwHH2K9WuZPApnHFCShrjOSvJs6sTWnvTNzk03g+bX9FDxBzY8x+A0qcX2RKElIl/OJ5FAKUU6q0/VscEn95PyPMS+2zdZvPwxZbft972Qa6uliXEdYWmiMDwQZQYwo5BhRWTRd3/GoDdWBClMacD9W+6njFSY1r6s1DBbCXuki9M5ta23vYfJoA+88RFvdmXCamQAAyeDORQk+TTiSEUVveFMQ8o5XolRMH9/wZvDvz86lLNnakFQttieqOWUVTcyE3qTHCvfv8JhTpyEYbVefGeejs9AsAvWXa74tn0UN3HnhkVBoLiEkxUeZXmPaa9TroRWrCFZmAQFlObEYHQYxnpgVZztI3XUm3Pl1F12TH7AzJwO03smYmtpsHYXIRLQLHYWiV3hkq+QCHm8Rde4qZKLJPchfLIpEPG1a/LcIpAnvNsUzo3AqCYX/jZGlSrz9RbwwBPtHGxMKLMIehJTG1S3109GW9WOavotC5lgeJuy7eCMcOBbSrGidTrsE/SIpMfLRa5Cv8k5FAgCWaM80Cwax0UGVuQt2KHDHtX1euJSUdof1ius/vkRNWID0GtrUnAgaVjWm9jmLEOMNrP/I5LZN0bT/7L5J0Ev6mq8aYESisAzGO3DA9pVK85kQtOFV+BcvBDzE3HmWt3+qQdwZSAu5ZTaG1097OdELH1nM7ZRzvx57UiqGDySbD7iAPegYijJ09o+rkPudM2AFcKMypEpAt9hGrV599rG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: phone-numbers
      namespace: quotes
