apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: quote-messenger
  namespace: quotes
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quote-messanger
              env:
              - name: TWILIO_AUTH
                valueFrom:
                  secretKeyRef:
                    name: twilio-auth-dev
                    key: id
              - name: PHONE_NUMBERS
                valueFrom:
                  secretKeyRef:
                    name: phone-numbers-dev
                    key: numbers