apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: quote-messenger
  namespace: quotes
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quote-messanger
              image: loganballard/quote-msg-arm:dev
              env:
              - name: TWILIO_AUTH
                valueFrom:
                  secretKeyRef:
                    name: twilio-auth-dev
                    key: id
              - name: PHONE_NUMBERS
                valueFrom:
                  secretKeyRef:
                    name: phone-numbers-dev
                    key: numbers
              - name: TZ
                value: "America/Los_Angeles"
              - name: ERR_NOTIFICATION_TOPIC
                value: "logyball_cat_of_the_day_err_notifications_dev"
              - name: ENVIRONMENT
                value: dev
              - name: ERROR_REPORT_ENABLED
                value: "true"
              - name: PUSH_TO_PROMETHEUS
                value: "true"
              - name: PROMETHEUS_GATEWAY_URI
                value: "http://prometheus-pushgateway.monitoring:9091/"
