apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: twilio-auth
  namespace: quotes
spec:
  encryptedData:
    id: AgC0Z+ui+lf2s039d85vZK/PEyZp9izNI379sxWBXVLx1soYohcKu3jBUtXaK/cLb92x9tBYq5ReqsUX2G3jgcac9p3AxXZB8QrgwwnOO3c9kQ5JUFWjLQhwt17QQCoNzboh4glIQI8aQD9T8V9znicZ6O4sHNC03BzUFi2tkv+JvrGXKcl+QOIDihpf81I7QdsGg0uMVU20DtMfpWEQDVfWG+nyTm++QZ/aBZ/oftf6/7Qrsqy+c2e7Sa1YtfC/BJbpeSVLKPYO9tWYbdPUbFuQhuqwtp5wc+Lhakz484JKRUXY6+OtAr+og/oci/tCUfpXwRk7xBsK0mCtMrWQW5uwHMWIJMtUk4MFog8stCSoiW414/FXutFfx2NAzdDxTt951voVfnrJrllx/xA2HxaYbbBzTaidg4/s5Fszs3Yc1kh4hwnG/XgWPvTi0opqVTpNt6YHyxT8uTESZbv+5usvrpNlR3jBXVblnEqqSx3zXKWCiuJnlxFjKEY1O5BRamVvZ+HWl9zJRGfwaOIKOxg0Z2tnMDWZt5kqYHb7C26o1PBMDxVFNPm9WKZq9KyUKcrQv2oRIXERZzewPN8hcmDwGfGCIFqUijYzvg6WFRe43hM3JqQZ37PdxWmraJ/mY5KJqleJGrB+PepDuPQamjAX73JsMbFVB3o5gaKbqh8+f4sGKxMhBtSGDrG5e3oY8YzKQpP/Rc1wL2V4LhquqrTloxT1wz1j1Hz4k9erJ989w/Y=
  template:
    metadata:
      creationTimestamp: null
      name: twilio-auth
      namespace: quotes
    type: Opaque
