name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: test
        run: go test -v ./...

      - name: build binary
        run: go build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: build docker image
#
#
#
#      - name: Tag
#          uses: K-Phoen/semver-release-action@master
#          with:
#            release_branch: main
#            release_strategy: none
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}